variable "SLACK_SIGNING_SECRET" {}
variable "SLACK_BOT_TOKEN" {}
variable "OPSGENIE_URL" {}
variable "OPSGENIE_TOKEN" {}
variable "AUTH_HEADER" {}
variable "PUSHOVER_URL" {}
variable "PUSHOVER_TOKEN" {}
variable "PUSHOVER_WEB3_GROUP" {}
variable "PUSHOVER_HUB_GROUP" {}
variable "PUSHOVER_TRADING_GROUP" {}
variable "PUSHOVER_BLOCKCHAIN_GROUP" {}
variable "PUSHOVER_MPC_GROUP" {}
variable "PUSHOVER_DEVOPS_GROUP" {}
variable "PUSHOVER_STAFF_GROUP" {}
variable "PUSHOVER_SECURITY_GROUP" {}
variable "OPSGENIE_WEB3_TEAM" {}
variable "OPSGENIE_HUB_TEAM" {}
variable "OPSGENIE_TRADING_TEAM" {}
variable "OPSGENIE_BLOCKCHAIN_TEAM" {}
variable "OPSGENIE_MPC_TEAM" {}
variable "OPSGENIE_DEVOPS_TEAM" {}
variable "OPSGENIE_STAFF_TEAM" {}
variable "OPSGENIE_SECURITY_TEAM" {}
variable "QCHAIN_AWS_REGION" {}
variable "QCHAIN_EKS_CLUSTER_NAME" {}
variable "QCHAIN_EKS_NAMESPACE" {}
